<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="12" hostname="DESKTOP-DJ4FDME" failures="6" tests="6" name="Test(failed)" time="0.177" errors="0" timestamp="2025-08-06T07:43:06 IST">
  <testcase classname="testngDemo.TestScenario6" name="fifth_testcase" time="0.04">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at testngDemo.TestScenario6.fifth_testcase(TestScenario6.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testngDemo.TestScenario6" name="first_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at testngDemo.TestScenario6.first_testcase(TestScenario6.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testngDemo.TestScenario" name="second_testcase" time="0.009">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hello World] but found [Hello]
at testngDemo.TestScenario.second_testcase(TestScenario.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="testngDemo.TestScenario" name="first_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at testngDemo.TestScenario.first_testcase(TestScenario.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="forth_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at testngDemo.TestScenario9.forth_testcase(TestScenario9.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="sixth_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at testngDemo.TestScenario9.sixth_testcase(TestScenario9.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testngDemo.TestScenario" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testngDemo.TestScenario" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testngDemo.TestScenario6" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testngDemo.TestScenario" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testngDemo.TestScenario6" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testngDemo.TestScenario6" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testngDemo.TestScenario" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="testngDemo.TestScenario9" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testngDemo.TestScenario6" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
</testsuite> <!-- Test(failed) -->
